//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_5_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalListCandidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocalListCandidate()
        {
            this.Debates = new HashSet<Debate>();
            this.Debates1 = new HashSet<Debate>();
        }
    
        public int CandidateID { get; set; }
        public string CandidateName { get; set; }
        public string NationalNumber { get; set; }
        public string Governorate { get; set; }
        public string ElectionArea { get; set; }
        public Nullable<int> NumberOfVotesCandidate { get; set; }
        public Nullable<int> LocalListingID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Debate> Debates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Debate> Debates1 { get; set; }
        public virtual LocalList LocalList { get; set; }
    }
}
